-- Convenience only — paste this ONE file into the Supabase SQL Editor
-- instead of running the 5 files under supabase/migrations/ one at a time.
-- Generated by concatenating (unmodified) the 5 pending migration files
-- listed in PENDING_MIGRATIONS.md, in the same order. Each block is
-- independently additive and idempotent (IF NOT EXISTS throughout) — safe
-- to run against the live database with no downtime, and safe to re-run if
-- it's ever partially applied. The individual files under
-- supabase/migrations/ remain the source of truth; keep this in sync with
-- them if either changes, or just re-run this generation manually before
-- next use — it's a snapshot, not a script that reads the others.

-- ── 1/5: 20260823_stripe_subscriptions.sql (Phase 2) ────────────────────────
ALTER TABLE "Clinic"
  ADD COLUMN IF NOT EXISTS "stripeCustomerId" text,
  ADD COLUMN IF NOT EXISTS "stripeSubscriptionId" text,
  ADD COLUMN IF NOT EXISTS "subscriptionStatus" text
    CHECK ("subscriptionStatus" IN (
      'trialing', 'active', 'past_due', 'canceled',
      'unpaid', 'incomplete', 'incomplete_expired', 'paused'
    )),
  ADD COLUMN IF NOT EXISTS "subscriptionCurrentPeriodEnd" timestamptz,
  ADD COLUMN IF NOT EXISTS "subscriptionItems" jsonb;

CREATE INDEX IF NOT EXISTS "idx_clinic_stripe_customer_id" ON "Clinic" ("stripeCustomerId");

-- ── 2/5: 20260824_pending_booking.sql (Phase 3) ─────────────────────────────
CREATE TABLE IF NOT EXISTS "PendingBooking" (
  id                       text PRIMARY KEY,
  "clinicId"               text NOT NULL REFERENCES "Clinic"(id),
  "doctorId"               text NOT NULL REFERENCES "Doctor"(id),
  "appointmentId"          text NOT NULL,
  "schedulerEventId"       text,
  timeslot                 timestamptz NOT NULL,
  "durationMinutes"        integer NOT NULL,
  "amountPaise"            integer NOT NULL,
  "bookingParams"          jsonb NOT NULL,
  status                   text NOT NULL DEFAULT 'pending',
  "stripeCheckoutSessionId" text,
  "expiresAt"              timestamptz NOT NULL,
  "createdAt"              timestamptz NOT NULL DEFAULT now(),
  "updatedAt"              timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS "PendingBooking"
  DROP CONSTRAINT IF EXISTS pending_booking_status_is_valid;

ALTER TABLE IF EXISTS "PendingBooking"
  ADD CONSTRAINT pending_booking_status_is_valid
    CHECK (status IN ('pending', 'completed', 'expired', 'cancelled'));

CREATE INDEX IF NOT EXISTS pending_booking_status_expires_idx
  ON "PendingBooking" (status, "expiresAt");

CREATE INDEX IF NOT EXISTS pending_booking_clinic_idx
  ON "PendingBooking" ("clinicId");

-- ── 3/5: 20260824_thread_booking_scope.sql (Phase 4) ────────────────────────
ALTER TABLE "Thread"
  ADD COLUMN IF NOT EXISTS "appointmentId" text REFERENCES "Appointment"(id),
  ADD COLUMN IF NOT EXISTS "doctorId" text REFERENCES "Doctor"(id),
  ADD COLUMN IF NOT EXISTS "scope" text NOT NULL DEFAULT 'general';

ALTER TABLE IF EXISTS "Thread"
  DROP CONSTRAINT IF EXISTS thread_scope_is_valid;

ALTER TABLE IF EXISTS "Thread"
  ADD CONSTRAINT thread_scope_is_valid
    CHECK (scope IN ('general', 'booking'));

CREATE UNIQUE INDEX IF NOT EXISTS thread_appointment_unique_idx
  ON "Thread" ("appointmentId")
  WHERE "appointmentId" IS NOT NULL;

CREATE INDEX IF NOT EXISTS thread_clinic_doctor_scope_idx
  ON "Thread" ("clinicId", "doctorId", scope);

-- ── 4/5: 20260824_thread_confirmed_patient.sql (Phase 6) ────────────────────
ALTER TABLE "Thread"
  ADD COLUMN IF NOT EXISTS "confirmedPatientId" text REFERENCES "Patient"(id);

-- ── 5/5: 20260824_clinic_google_review_url.sql (Phase 7) ────────────────────
ALTER TABLE "Clinic"
  ADD COLUMN IF NOT EXISTS "googleReviewUrl" text;
